name: Deploy to Amazon ECR

on:
  push:
    branches:
      - main  # main 브랜치에 push할 때
  pull_request:
    branches:
      - main  # main 브랜치에 PR할 때 실행한다.
env: # 사용할 env	
  AWS_REGION: ap-northeast-2
  ECR_REGISTRY: 405906814034.dkr.ecr.ap-northeast-2.amazonaws.com
  ECR_REPOSITORY: feelin-dev/feelin-web
jobs:	
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials	# AWS 로그인
        uses: aws-actions/configure-aws-credentials@v1
        with:	# AWS 로그인에 필요한 정보들. 얘네는 Github Secret에 설정해야 한다.
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR # ECR에도 로그인
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR # 이미지 빌드하고 ECR push
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
       # 아래처럼 docker 커맨드를 실행한다.
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:latest"
